DANE:
    API_URL: 'http://localhost:5500/DANE/'
    MANAGE_URL: 'http://localhost:5500/manage/'
RABBITMQ:
    HOST: 'dane-rabbitmq-api.default.svc.cluster.local'
    PORT: 5672
    EXCHANGE: 'DANE-exchange'
    RESPONSE_QUEUE: 'DANE-response-queue'
    USER: 'guest' # change this for production mode
    PASSWORD: 'guest' # change this for production mode
ELASTICSEARCH:
    HOST: ['elasticsearch']
    PORT: 9200
    USER: 'elastic' # change this for production mode
    PASSWORD: 'changeme' # change this for production mode
    SCHEME: 'http'
LOGGING:
    DIR: "./dane-server-logs/"
    LEVEL: "DEBUG"
DANE_SERVER:
    TEMP_FOLDER: "/mnt/dane-fs/input-files"
    OUT_FOLDER: "/mnt/dane-fs/output-files" # each worker should put his output in a subfolder of this dir
    ES_INDEX: 'dane-index-k8s-asr' # configure a different index per DANE environment (when using the same ES cluster!)